"""
cli/scaffold.py
===============
`macro-deck new-plugin` command — scaffolds a new Python extension.

Usage:
    python -m macro_deck_python new-plugin "My Plugin Name" --id me.myplugin
    python -m macro_deck_python new-plugin "Twitch Stats" --id me.twitch --author "Your Name"
    python -m macro_deck_python new-plugin "OBS Extras" --id me.obs --style class
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


# ── Templates ─────────────────────────────────────────────────────────

_MANIFEST_TEMPLATE = """\
{{
  "package_id": "{package_id}",
  "name": "{name}",
  "version": "1.0.0",
  "author": "{author}",
  "description": "{description}",
  "target_api_version": 20
}}
"""

_MAIN_DECORATOR_TEMPLATE = '''\
"""
{name} — Macro Deck Python Extension
Author: {author}

This plugin was generated by `macro-deck new-plugin`.
Edit this file to implement your actions.

Documentation:
  https://github.com/Macro-Deck-App/Macro-Deck/wiki/Plugin-API
"""
from __future__ import annotations
import json
from macro_deck_python.sdk import (
    PluginBase, action, on_load, on_delete,
    VariableType, set_variable, get_variable,
    get_config, set_config, log_info, log_error,
)


class Main(PluginBase):
    package_id  = "{package_id}"
    name        = "{name}"
    version     = "1.0.0"
    author      = "{author}"
    description = "{description}"
    can_configure = False

    def enable(self):
        """Called when the plugin is loaded. Call super().enable() to discover @action methods."""
        super().enable()
        log_info(self, f"{{self.name}} loaded with {{len(self.actions)}} action(s)")

    def disable(self):
        """Called when the plugin is unloaded. Clean up any background threads here."""
        log_info(self, f"{{self.name}} unloaded")

    # ── Actions ───────────────────────────────────────────────────────

    @action(
        name="Hello World",
        description="A simple example action that logs a message",
        can_configure=False,
    )
    def hello_world(self, client_id: str, button):
        """This method is called when the button is pressed."""
        log_info(self, f"Hello from {{self.name}}! Triggered by {{client_id}}")

    @action(
        name="Configurable Action",
        description="An action that reads its JSON configuration",
        can_configure=True,
    )
    def configurable(self, client_id: str, button):
        """Read configuration with self.get_config() inside an @action method."""
        # In @action methods, read config via the action's own configuration attribute
        # (set by Macro Deck when the user saves the action configurator)
        cfg = json.loads(self.configuration) if self.configuration else {{}}
        text = cfg.get("text", "default value")
        log_info(self, f"Configurable triggered: text={{text!r}}")

    @action(
        name="Set Variable",
        description="Example: set a variable and use it in button labels",
        can_configure=False,
    )
    def set_counter(self, client_id: str, button):
        current = get_variable("{safe_id}_counter") or 0
        new_val = int(current) + 1
        set_variable("{safe_id}_counter", new_val, VariableType.INTEGER, self)
        log_info(self, f"Counter is now {{new_val}}")

    # ── Lifecycle hooks ───────────────────────────────────────────────

    @on_load("configurable")
    def configurable_loaded(self):
        """Called when a button with the 'configurable' action is loaded."""
        log_info(self, "A configurable button was loaded")

    @on_delete("configurable")
    def configurable_deleted(self):
        """Called when a button with the 'configurable' action is deleted."""
        log_info(self, "A configurable button was deleted")
'''

_MAIN_CLASS_TEMPLATE = '''\
"""
{name} — Macro Deck Python Extension (class style)
Author: {author}

This plugin was generated by `macro-deck new-plugin`.
"""
from __future__ import annotations
import json
import logging
from typing import List, TYPE_CHECKING
from macro_deck_python.sdk import PluginBase, ActionBase, VariableType
from macro_deck_python.sdk import set_variable, get_variable, log_info, log_error

if TYPE_CHECKING:
    from macro_deck_python.models.action_button import ActionButton

logger = logging.getLogger("plugin.{safe_id}")


# ── Define each action as its own class ──────────────────────────────

class HelloAction(ActionBase):
    action_id   = "hello"
    name        = "Hello World"
    description = "A simple example action"
    can_configure = False

    def trigger(self, client_id: str, button: "ActionButton") -> None:
        log_info(self.plugin, f"Hello from {{client_id}}!")

    def on_action_button_loaded(self) -> None:
        log_info(self.plugin, "hello button loaded")

    def on_action_button_delete(self) -> None:
        log_info(self.plugin, "hello button deleted")


class ConfigurableAction(ActionBase):
    action_id   = "configurable"
    name        = "Configurable Action"
    description = "Reads JSON configuration"
    can_configure = True

    def trigger(self, client_id: str, button: "ActionButton") -> None:
        text = self.get_config("text", "default")
        log_info(self.plugin, f"text={{text!r}}")


class CounterAction(ActionBase):
    action_id   = "counter"
    name        = "Increment Counter"
    description = "Increment a variable each press"
    can_configure = False

    def trigger(self, client_id: str, button: "ActionButton") -> None:
        current = get_variable("{safe_id}_counter") or 0
        new_val = int(current) + 1
        set_variable("{safe_id}_counter", new_val, VariableType.INTEGER, self.plugin)


# ── Main plugin class ─────────────────────────────────────────────────

class Main(PluginBase):
    package_id  = "{package_id}"
    name        = "{name}"
    version     = "1.0.0"
    author      = "{author}"
    description = "{description}"
    can_configure = False

    def enable(self) -> None:
        super().enable()   # loads any @action decorators (none here)
        self.actions.extend([
            HelloAction(),
            ConfigurableAction(),
            CounterAction(),
        ])
        log_info(self, f"{{self.name}} loaded with {{len(self.actions)}} action(s)")

    def disable(self) -> None:
        log_info(self, f"{{self.name}} unloaded")
'''

_REQUIREMENTS_TEMPLATE = """\
# Add your plugin's pip dependencies here, one per line.
# They will be auto-installed when Macro Deck loads your plugin.
# Example:
# requests>=2.28.0
# pillow>=10.0.0
"""

_README_TEMPLATE = """\
# {name}

A Macro Deck Python extension by {author}.

## Actions

| Action ID       | Name               | Configurable |
|-----------------|--------------------|:------------:|
| hello_world     | Hello World        | No           |
| configurable    | Configurable Action| Yes          |
| set_counter     | Set Variable       | No           |

## Configuration

Each action can store a JSON configuration string. When `can_configure=True`,
Macro Deck's configurator UI lets users edit it via the REST API.

## Variables

| Variable name        | Type    | Description          |
|----------------------|---------|----------------------|
| {safe_id}_counter    | Integer | Increments each press|

## Development

Edit `main.py` and save — Macro Deck will hot-reload your plugin automatically.

## Requirements

Add any pip dependencies to `requirements.txt`.
"""


# ── Scaffold function ──────────────────────────────────────────────────

def _slugify(name: str) -> str:
    """'My Cool Plugin' → 'my_cool_plugin'"""
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def scaffold(
    name: str,
    package_id: str,
    author: str = "Unknown",
    description: str = "",
    style: str = "decorator",
    output_dir: Optional[Path] = None,
) -> Path:
    """
    Scaffold a new plugin directory.

    Returns the created directory path.
    """
    from typing import Optional

    if not description:
        description = f"A Macro Deck extension: {name}"

    safe_id = _slugify(package_id.split(".")[-1])

    if output_dir is None:
        output_dir = Path.home() / ".macro_deck" / "plugins" / package_id
    else:
        output_dir = Path(output_dir) / package_id

    if output_dir.exists():
        raise FileExistsError(
            f"Plugin directory already exists: {output_dir}\n"
            "Delete it first or choose a different package_id."
        )
    output_dir.mkdir(parents=True)

    ctx = dict(
        package_id=package_id,
        name=name,
        author=author,
        description=description,
        safe_id=safe_id,
    )

    # manifest.json
    (output_dir / "manifest.json").write_text(
        _MANIFEST_TEMPLATE.format(**ctx)
    )

    # main.py
    template = _MAIN_DECORATOR_TEMPLATE if style == "decorator" else _MAIN_CLASS_TEMPLATE
    (output_dir / "main.py").write_text(template.format(**ctx))

    # requirements.txt
    (output_dir / "requirements.txt").write_text(_REQUIREMENTS_TEMPLATE)

    # README.md
    (output_dir / "README.md").write_text(_README_TEMPLATE.format(**ctx))

    # config.json (empty)
    (output_dir / "config.json").write_text("{}")

    return output_dir


# ── CLI entry point ───────────────────────────────────────────────────

def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        prog="macro-deck new-plugin",
        description="Scaffold a new Macro Deck Python extension",
    )
    p.add_argument("name", help='Human-readable plugin name, e.g. "My Plugin"')
    p.add_argument("--id",     required=True, dest="package_id",
                   help='Package ID, e.g. "me.myplugin"')
    p.add_argument("--author", default="Unknown", help="Your name")
    p.add_argument("--desc",   default="",        help="Short description")
    p.add_argument("--style",  default="decorator",
                   choices=["decorator", "class"],
                   help="Authoring style: decorator (default) or class")
    p.add_argument("--out",    default=None,
                   help="Output parent directory (default: ~/.macro_deck/plugins)")
    args = p.parse_args(argv)

    try:
        out = scaffold(
            name=args.name,
            package_id=args.package_id,
            author=args.author,
            description=args.desc,
            style=args.style,
            output_dir=Path(args.out) if args.out else None,
        )
        print(f"\n✅ Plugin scaffolded at:\n   {out}\n")
        print("Next steps:")
        print(f"  1. Edit  {out}/main.py  to implement your actions")
        print(f"  2. Add pip dependencies to  {out}/requirements.txt")
        print(f"  3. Start Macro Deck — it will load your plugin automatically\n")
        return 0
    except FileExistsError as exc:
        print(f"❌ {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"❌ Scaffold failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
